export const ganttData = [
  {
    id: 1,
    codigo: 'PRO-001',
    nombre: 'Fortalecimiento de Capacidades Productivas',
    inicio: new Date(2026, 0, 1),
    fin: new Date(2026, 11, 31),
    progreso: 42,
    expanded: true,
    children: [
      {
        id: 2,
        codigo: 'ACT-001',
        nombre: 'Capacitación a productores',
        inicio: new Date(2026, 0, 5),
        fin: new Date(2026, 2, 30),
        progreso: 80,
        expanded: true,
        children: [
          {
            id: 3,
            codigo: 'TAR-001',
            nombre: 'Elaboración del material',
            inicio: new Date(2026, 0, 5),
            fin: new Date(2026, 0, 20),
            progreso: 100,
          },
          {
            id: 4,
            codigo: 'TAR-002',
            nombre: 'Primer taller',
            inicio: new Date(2026, 1, 1),
            fin: new Date(2026, 1, 15),
            progreso: 100,
          },
          {
            id: 5,
            codigo: 'TAR-003',
            nombre: 'Segundo taller',
            inicio: new Date(2026, 2, 1),
            fin: new Date(2026, 2, 20),
            progreso: 65,
          },
        ],
      },
      {
        id: 6,
        codigo: 'ACT-002',
        nombre: 'Asistencia Técnica',
        inicio: new Date(2026, 3, 1),
        fin: new Date(2026, 5, 30),
        progreso: 25,
        expanded: true,
        children: [
          {
            id: 7,
            codigo: 'TAR-004',
            nombre: 'Diagnóstico',
            inicio: new Date(2026, 3, 1),
            fin: new Date(2026, 3, 20),
            progreso: 100,
          },
          {
            id: 8,
            codigo: 'TAR-005',
            nombre: 'Seguimiento',
            inicio: new Date(2026, 4, 1),
            fin: new Date(2026, 5, 30),
            progreso: 15,
          },
        ],
      },
    ],
  },
]
