<template>
  <div>
    <h1>Notificaciones</h1>
    <!-- <indicador-line-chart></indicador-line-chart> -->
    <!-- Botón para abrir el modal -->
    <v-btn
      color="blue-darken-1"
      variant="elevated"
      block
      size="large"
      @click="modalAbierto = true"
      class="rounded-lg"
    >
      Abrir Registro de Bitácora
    </v-btn>
    <indicador-registro-bitacora
      v-model="modalAbierto"
      :idactividad="idactividad"
    ></indicador-registro-bitacora>

    <encabezado-contribucion
      :datos-estructura="estructuraProcedencia"
      @payload-actualizado="recibirContribuciones"
    ></encabezado-contribucion>
    <gestion-copias-planificacion></gestion-copias-planificacion>
  </div>
  <h1>Contribuciones</h1>
  {{ proyectoContribuciones }}
</template>

<script setup>
import { ref } from 'vue'
import IndicadorLineChart from '@/modules/reportes/components/partials-indicador-registro/IndicadorLineChart.vue'
import IndicadorRegistroBitacora from '@/modules/reportes/components/IndicadorRegistroBitacora.vue'
import EncabezadoContribucion from '@/modules/formularios/components/EncabezadoContribucion.vue'
import GestionCopiasPlanificacion from '@/modules/planificacionxls/components/gestion-seguimiento/GestionCopiasPlanificacion.vue'

const idactividad = ref(1)

const modalAbierto = ref(false)

//Funcion para recibir los datos de las contribuciones
const recibirContribuciones = (payload) => {
  console.log('Payload recibido:', payload)
  proyectoContribuciones.value = payload
}

const proyectoContribuciones = ref()

const estructuraProcedencia = ref({
  datosProcedencia: {
    objetivogeneral: {
      tipo: 'objetivogeneral',
      data: {
        id: 1,
        kpis: [],
        indicador_og: [
          {
            id: 1,
            codigo: 'IND001-OO',
            descripcion:
              'Actas, listas de participantes, reportes de actividades, políticas públicas propuestas o formuladas, fotografías.',
            redaccion: 'GUIA',
            fuente_verificacion: 'Fuentes de verificacion',
            target_poblacion: '',
            fechaTargetPoblacion: null,
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: null,
            baseline: '',
            fechaLineaBase: null,
            target_q1: '',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 29,
            objetivo_general: 1,
          },
        ],
        resultados_og: [],
        objetivos_especificos_og: [
          {
            id: 1,
            indicador_oe: [
              {
                id: 3,
                codigo: 'IND001-SPO1',
                descripcion: 'Documento de propuesta de Politica Publica de Educacion',
                redaccion: 'SMART',
                fuente_verificacion: '',
                target_poblacion: '',
                fechaTargetPoblacion: null,
                tipo: 'A-Z',
                frecuencia: 'MENSUAL',
                responsable: '',
                baseline: '0',
                fechaLineaBase: null,
                target_q1: '1',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 28,
                objetivo_especifico: 1,
              },
            ],
            resultados_oe: [
              {
                id: 1,
                indicador_res_oe: [
                  {
                    id: 2,
                    codigo: 'IND001-RES01-SPO1',
                    descripcion:
                      'Prueba de ingreso y salida de los procesos de formación, modulos de formación, materiales listas de participantes, fotografías.',
                    redaccion: 'GUIA',
                    fuente_verificacion: '',
                    target_poblacion: '1',
                    fechaTargetPoblacion: null,
                    tipo: '1-9',
                    frecuencia: 'MENSUAL',
                    responsable: null,
                    baseline: '0',
                    fechaLineaBase: null,
                    target_q1: '40',
                    fechaTargetQ1: null,
                    target_q2: '',
                    fechaTargetQ2: null,
                    target_q3: '',
                    fechaTargetQ3: null,
                    target_q4: null,
                    fechaTargetQ4: null,
                    polymorphic_ctype: 33,
                    resultado_obj_especifico: 1,
                  },
                ],
                productos_res_oe: [],
                proceso_resultado_oe: [],
                actividad_resultado_oe: [],
                codigo: 'RES01-SPO1',
                descripcion:
                  "Representantes de 5 Federaciones Nacionales (FEBOPDIF, FENACIEBO, FEBOLDI, FEBOLDIPSI, FEBOS), el Comité Nacional de Educación Inclusiva y el Comité Nacional de Incidencia, se han articulado y fortalecido capacidades en incidencia política, enfoque de género, el derecho a defender derechos, educación inclusiva, comunicación para la incidencia y metodologías de diálogos multiactor.', 'SUp Res OE",
                supuestos: '',
                riesgos: '',
                polymorphic_ctype: 31,
                objetivo_especifico: 1,
              },
              {
                id: 2,
                indicador_res_oe: [],
                productos_res_oe: [],
                proceso_resultado_oe: [],
                actividad_resultado_oe: [],
                codigo: 'RES02-SPO1',
                descripcion:
                  'Federaciones Nacionales de personas con discapacidad y Comités Nacionales articulados, inciden en la implementación de una política pública de educación inclusiva para personas con discapacidad, con autoridades nacionales, OPD y sociedad civil.',
                supuestos: '',
                riesgos: '',
                polymorphic_ctype: 31,
                objetivo_especifico: 1,
              },
              {
                id: 3,
                indicador_res_oe: [],
                productos_res_oe: [],
                proceso_resultado_oe: [],
                actividad_resultado_oe: [],
                codigo: 'RES03-SPO1',
                descripcion: 'Gestión eficaz del proyecto',
                supuestos: '',
                riesgos: '',
                polymorphic_ctype: 31,
                objetivo_especifico: 1,
              },
            ],
            productos_oe: [],
            codigo: 'SPO1',
            descripcion:
              'Promover la articulación entre las Federaciones de personas con discapacidad (OPD); FEBOPDIF, FENACIEBO, FEBOLDI, FEBOLDIPSI, FEBOS, el Comité Nacional de Educación Inclusiva y el Comité de Incidencia Política, para la formulación de una Política Pública de Educación Inclusiva para personas con discapacidad.',
            supuestos: '',
            riesgos: '',
            proyecto: null,
            objetivo_general: 1,
          },
        ],
        codigo: 'OO',
        descripcion:
          "Contribuir al fortalecimiento de competencias estratégicas y capacidades de mujeres y hombres dirigentes con discapacidad de organizaciones nacionales, para promover la inclusión social, el ejercicio del derecho a la educación, y el diálogo multiactor, facilitando su acceso a espacios público-políticos para la formulación de políticas inclusivas.', 'sup og",
        supuestos: '',
        riesgos:
          'Injerencia Político-Partidaria en las OPD: La politización de las OPD puede llevar a conflictos de interés y comprometer la independencia y eficacia de las organizaciones en la promoción de los derechos de las personas con discapacidad.',
        proyecto: 1,
      },
    },
    indicadorog: [
      {
        tipo: 'indicadorog',
        data: {
          id: 1,
          codigo: 'IND001-OO',
          descripcion:
            'Actas, listas de participantes, reportes de actividades, políticas públicas propuestas o formuladas, fotografías.',
          redaccion: 'GUIA',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '',
          fechaTargetPoblacion: null,
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: null,
          baseline: '',
          fechaLineaBase: null,
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          target_q4: null,
          fechaTargetQ4: null,
          polymorphic_ctype: 29,
          objetivo_general: 1,
        },
      },
    ],
    objetivoespecificoog: {
      tipo: 'objetivoespecificoog',
      data: {
        id: 1,
        indicador_oe: [
          {
            id: 3,
            codigo: 'IND001-SPO1',
            descripcion: 'Documento de propuesta de Politica Publica de Educacion',
            redaccion: 'SMART',
            fuente_verificacion: '',
            target_poblacion: '',
            fechaTargetPoblacion: null,
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: '',
            baseline: '0',
            fechaLineaBase: null,
            target_q1: '1',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 28,
            objetivo_especifico: 1,
          },
        ],
        resultados_oe: [
          {
            id: 1,
            indicador_res_oe: [
              {
                id: 2,
                codigo: 'IND001-RES01-SPO1',
                descripcion:
                  'Prueba de ingreso y salida de los procesos de formación, modulos de formación, materiales listas de participantes, fotografías.',
                redaccion: 'GUIA',
                fuente_verificacion: '',
                target_poblacion: '1',
                fechaTargetPoblacion: null,
                tipo: '1-9',
                frecuencia: 'MENSUAL',
                responsable: null,
                baseline: '0',
                fechaLineaBase: null,
                target_q1: '40',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 33,
                resultado_obj_especifico: 1,
              },
            ],
            productos_res_oe: [],
            proceso_resultado_oe: [],
            actividad_resultado_oe: [],
            codigo: 'RES01-SPO1',
            descripcion:
              "Representantes de 5 Federaciones Nacionales (FEBOPDIF, FENACIEBO, FEBOLDI, FEBOLDIPSI, FEBOS), el Comité Nacional de Educación Inclusiva y el Comité Nacional de Incidencia, se han articulado y fortalecido capacidades en incidencia política, enfoque de género, el derecho a defender derechos, educación inclusiva, comunicación para la incidencia y metodologías de diálogos multiactor.', 'SUp Res OE",
            supuestos: '',
            riesgos: '',
            polymorphic_ctype: 31,
            objetivo_especifico: 1,
          },
          {
            id: 2,
            indicador_res_oe: [],
            productos_res_oe: [],
            proceso_resultado_oe: [],
            actividad_resultado_oe: [],
            codigo: 'RES02-SPO1',
            descripcion:
              'Federaciones Nacionales de personas con discapacidad y Comités Nacionales articulados, inciden en la implementación de una política pública de educación inclusiva para personas con discapacidad, con autoridades nacionales, OPD y sociedad civil.',
            supuestos: '',
            riesgos: '',
            polymorphic_ctype: 31,
            objetivo_especifico: 1,
          },
          {
            id: 3,
            indicador_res_oe: [],
            productos_res_oe: [],
            proceso_resultado_oe: [],
            actividad_resultado_oe: [],
            codigo: 'RES03-SPO1',
            descripcion: 'Gestión eficaz del proyecto',
            supuestos: '',
            riesgos: '',
            polymorphic_ctype: 31,
            objetivo_especifico: 1,
          },
        ],
        productos_oe: [],
        codigo: 'SPO1',
        descripcion:
          'Promover la articulación entre las Federaciones de personas con discapacidad (OPD); FEBOPDIF, FENACIEBO, FEBOLDI, FEBOLDIPSI, FEBOS, el Comité Nacional de Educación Inclusiva y el Comité de Incidencia Política, para la formulación de una Política Pública de Educación Inclusiva para personas con discapacidad.',
        supuestos: '',
        riesgos: '',
        proyecto: null,
        objetivo_general: 1,
      },
    },
    indicadoroe: {
      tipo: 'indicadoroe',
      data: {
        id: 3,
        codigo: 'IND001-SPO1',
        descripcion: 'Documento de propuesta de Politica Publica de Educacion',
        redaccion: 'SMART',
        fuente_verificacion: '',
        target_poblacion: '',
        fechaTargetPoblacion: null,
        tipo: 'A-Z',
        frecuencia: 'MENSUAL',
        responsable: '',
        baseline: '0',
        fechaLineaBase: null,
        target_q1: '1',
        fechaTargetQ1: null,
        target_q2: '',
        fechaTargetQ2: null,
        target_q3: '',
        fechaTargetQ3: null,
        target_q4: null,
        fechaTargetQ4: null,
        polymorphic_ctype: 28,
        objetivo_especifico: 1,
      },
    },
    resultadooe: {
      tipo: 'resultadooe',
      data: {
        id: 1,
        indicador_res_oe: [
          {
            id: 2,
            codigo: 'IND001-RES01-SPO1',
            descripcion:
              'Prueba de ingreso y salida de los procesos de formación, modulos de formación, materiales listas de participantes, fotografías.',
            redaccion: 'GUIA',
            fuente_verificacion: '',
            target_poblacion: '1',
            fechaTargetPoblacion: null,
            tipo: '1-9',
            frecuencia: 'MENSUAL',
            responsable: null,
            baseline: '0',
            fechaLineaBase: null,
            target_q1: '40',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 33,
            resultado_obj_especifico: 1,
          },
        ],
        productos_res_oe: [],
        proceso_resultado_oe: [],
        actividad_resultado_oe: [],
        codigo: 'RES01-SPO1',
        descripcion:
          "Representantes de 5 Federaciones Nacionales (FEBOPDIF, FENACIEBO, FEBOLDI, FEBOLDIPSI, FEBOS), el Comité Nacional de Educación Inclusiva y el Comité Nacional de Incidencia, se han articulado y fortalecido capacidades en incidencia política, enfoque de género, el derecho a defender derechos, educación inclusiva, comunicación para la incidencia y metodologías de diálogos multiactor.', 'SUp Res OE",
        supuestos: '',
        riesgos: '',
        polymorphic_ctype: 31,
        objetivo_especifico: 1,
      },
    },
    indicadorroe: {
      tipo: 'indicadorroe',
      data: {
        id: 2,
        codigo: 'IND001-RES01-SPO1',
        descripcion:
          'Prueba de ingreso y salida de los procesos de formación, modulos de formación, materiales listas de participantes, fotografías.',
        redaccion: 'GUIA',
        fuente_verificacion: '',
        target_poblacion: '1',
        fechaTargetPoblacion: null,
        tipo: '1-9',
        frecuencia: 'MENSUAL',
        responsable: null,
        baseline: '0',
        fechaLineaBase: null,
        target_q1: '40',
        fechaTargetQ1: null,
        target_q2: '',
        fechaTargetQ2: null,
        target_q3: '',
        fechaTargetQ3: null,
        target_q4: null,
        fechaTargetQ4: null,
        polymorphic_ctype: 33,
        resultado_obj_especifico: 1,
      },
    },
  },
  nodosRelacionados: [
    {
      id: '2',
      type: 'objetivogeneral',
      dimensions: {
        width: 700,
        height: 309,
      },
      computedPosition: {
        x: 1500,
        y: 650,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-2',
            type: 'source',
            nodeId: '2',
            position: 'bottom',
            x: 344,
            y: 303.4375,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-2',
            type: 'target',
            nodeId: '2',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1500,
        y: 650,
      },
      data: {
        label: 'Objetivo General',
        type: 'objetivogeneral',
        estado: 'ES',
        mapaNodoId: '1',
        nodoProyecto: {
          id: 1,
          codigo: 'OO',
          descripcion:
            "Contribuir al fortalecimiento de competencias estratégicas y capacidades de mujeres y hombres dirigentes con discapacidad de organizaciones nacionales, para promover la inclusión social, el ejercicio del derecho a la educación, y el diálogo multiactor, facilitando su acceso a espacios público-políticos para la formulación de políticas inclusivas.', 'sup og",
          supuestos: '',
          riesgos:
            'Injerencia Político-Partidaria en las OPD: La politización de las OPD puede llevar a conflictos de interés y comprometer la independencia y eficacia de las organizaciones en la promoción de los derechos de las personas con discapacidad.',
          proyecto: 1,
        },
      },
      events: {},
    },
    {
      id: '4',
      type: 'indicadorog',
      dimensions: {
        width: 700,
        height: 533,
      },
      computedPosition: {
        x: 1875,
        y: 1300,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-4',
            type: 'source',
            nodeId: '4',
            position: 'bottom',
            x: 344,
            y: 526.875,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-4',
            type: 'target',
            nodeId: '4',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1875,
        y: 1300,
      },
      data: {
        label: 'Indicador OG',
        type: 'indicadorog',
        estado: 'ES',
        mapaNodoId: '1',
        nodoProyecto: {
          id: 1,
          codigo: 'IND001-OO',
          descripcion:
            'Actas, listas de participantes, reportes de actividades, políticas públicas propuestas o formuladas, fotografías.',
          redaccion: 'GUIA',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '',
          fechaTargetPoblacion: null,
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: null,
          baseline: '',
          fechaLineaBase: null,
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          objetivo_general: 1,
        },
      },
      events: {},
    },
    {
      id: '3',
      type: 'objetivoespecificoog',
      dimensions: {
        width: 700,
        height: 270,
      },
      computedPosition: {
        x: 1125,
        y: 1300,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-3',
            type: 'source',
            nodeId: '3',
            position: 'bottom',
            x: 344,
            y: 263.5625,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-3',
            type: 'target',
            nodeId: '3',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1125,
        y: 1300,
      },
      data: {
        label: 'Objetivo Especifico OG',
        type: 'objetivoespecificoog',
        mapaNodoId: '1',
        nodoProyecto: {
          id: 1,
          codigo: 'SPO1',
          descripcion:
            'Promover la articulación entre las Federaciones de personas con discapacidad (OPD); FEBOPDIF, FENACIEBO, FEBOLDI, FEBOLDIPSI, FEBOS, el Comité Nacional de Educación Inclusiva y el Comité de Incidencia Política, para la formulación de una Política Pública de Educación Inclusiva para personas con discapacidad.',
          supuestos: '',
          riesgos: '',
          proyecto: null,
          objetivo_general: 1,
        },
      },
      events: {},
    },
    {
      id: '9',
      type: 'indicadoroe',
      dimensions: {
        width: 700,
        height: 513,
      },
      computedPosition: {
        x: 2250,
        y: 1950,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-9',
            type: 'source',
            nodeId: '9',
            position: 'bottom',
            x: 344,
            y: 506.9375,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-9',
            type: 'target',
            nodeId: '9',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 2250,
        y: 1950,
      },
      data: {
        label: 'Indicador OE',
        type: 'indicadoroe',
        estado: 'ES',
        mapaNodoId: '1',
        nodoProyecto: {
          id: 3,
          codigo: 'IND001-SPO1',
          descripcion: 'Documento de propuesta de Politica Publica de Educacion',
          redaccion: 'SMART',
          fuente_verificacion: '',
          target_poblacion: '',
          fechaTargetPoblacion: null,
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: '',
          baseline: '0',
          fechaLineaBase: null,
          target_q1: '1',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          objetivo_especifico: 1,
        },
      },
      events: {},
    },
    {
      id: '5',
      type: 'resultadooe',
      dimensions: {
        width: 700,
        height: 290,
      },
      computedPosition: {
        x: 0,
        y: 1950,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-5',
            type: 'source',
            nodeId: '5',
            position: 'bottom',
            x: 344,
            y: 283.5,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-5',
            type: 'target',
            nodeId: '5',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 0,
        y: 1950,
      },
      data: {
        label: 'Resultado OE',
        type: 'resultadooe',
        estado: 'ES',
        mapaNodoId: '1',
        nodoProyecto: {
          id: 1,
          codigo: 'RES01-SPO1',
          descripcion:
            "Representantes de 5 Federaciones Nacionales (FEBOPDIF, FENACIEBO, FEBOLDI, FEBOLDIPSI, FEBOS), el Comité Nacional de Educación Inclusiva y el Comité Nacional de Incidencia, se han articulado y fortalecido capacidades en incidencia política, enfoque de género, el derecho a defender derechos, educación inclusiva, comunicación para la incidencia y metodologías de diálogos multiactor.', 'SUp Res OE",
          supuestos: '',
          riesgos: '',
          proceso: null,
          objetivo_especifico: 1,
        },
      },
      events: {},
    },
    {
      id: '8',
      type: 'indicadorroe',
      dimensions: {
        width: 700,
        height: 541,
      },
      computedPosition: {
        x: 0,
        y: 2600,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-8',
            type: 'source',
            nodeId: '8',
            position: 'bottom',
            x: 344,
            y: 534.875,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-8',
            type: 'target',
            nodeId: '8',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 0,
        y: 2600,
      },
      data: {
        label: 'Indicador Resultado OE',
        type: 'indicadorroe',
        mapaNodoId: '1',
        nodoProyecto: {
          id: 2,
          codigo: 'IND001-RES01-SPO1',
          descripcion:
            'Prueba de ingreso y salida de los procesos de formación, modulos de formación, materiales listas de participantes, fotografías.',
          redaccion: 'GUIA',
          fuente_verificacion: '',
          target_poblacion: '1',
          fechaTargetPoblacion: null,
          tipo: '1-9',
          frecuencia: 'MENSUAL',
          responsable: null,
          baseline: '0',
          fechaLineaBase: null,
          target_q1: '40',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
        },
      },
      events: {},
    },
  ],
  seleccionesSimples: {
    objetivoGeneralId: 1,
    indicadorOGIds: [1],
    objetivoEspecificoId: 1,
    indicadorOEId: 3,
    resultadoOEId: 1,
    indicadorResultadoOEId: 2,
  },
})

// const estructuraProcedencia = ref({
//   datosProcedencia: {
//     objetivogeneral: {
//       tipo: 'objetivogeneral',
//       data: {
//         id: 6,
//         kpis: [],
//         indicador_og: [
//           {
//             id: 27,
//             codigo: 'IND002-OG',
//             descripcion: 'IND002-OG',
//             redaccion: 'SMART',
//             fuente_verificacion: 'Fuentes de verificacion',
//             target_poblacion: '50',
//             fechaTargetPoblacion: '2025-11-09',
//             tipo: 'A-Z',
//             frecuencia: 'MENSUAL',
//             responsable: null,
//             baseline: '0',
//             fechaLineaBase: '2025-09-11',
//             target_q1: '',
//             fechaTargetQ1: null,
//             target_q2: '',
//             fechaTargetQ2: null,
//             target_q3: '',
//             fechaTargetQ3: null,
//             target_q4: null,
//             fechaTargetQ4: null,
//             polymorphic_ctype: 29,
//             objetivo_general: 6,
//           },
//           {
//             id: 28,
//             codigo: 'IND0001-OG',
//             descripcion: 'Descripcion del IND0001-OG',
//             redaccion: 'SMART',
//             fuente_verificacion: 'Fuentes de verificacion',
//             target_poblacion: '100',
//             fechaTargetPoblacion: '2025-11-09',
//             tipo: '1-9',
//             frecuencia: 'CUATRIMESTRAL',
//             responsable: null,
//             baseline: '10',
//             fechaLineaBase: '2025-09-01',
//             target_q1: '30',
//             fechaTargetQ1: '2025-09-17',
//             target_q2: '40',
//             fechaTargetQ2: '2025-10-01',
//             target_q3: '50',
//             fechaTargetQ3: '2025-10-08',
//             target_q4: null,
//             fechaTargetQ4: null,
//             polymorphic_ctype: 29,
//             objetivo_general: 6,
//           },
//         ],
//         resultados_og: [
//           {
//             id: 11,
//             indicador_res_og: [],
//             proceso_resultado_og: [
//               {
//                 id: 6,
//                 actividades: [],
//                 codigo: 'PROC001-R01-OO',
//                 titulo: 'Procesos Res OG',
//                 descripcion: '',
//                 resultado_og: 11,
//                 resultado_oe: null,
//                 producto_oe: null,
//               },
//             ],
//             actividad_resultado_og: [],
//             codigo: 'R01-OO',
//             descripcion: 'Descripcion del resultado de obj gral',
//             supuestos: 'sup res obj gral',
//             riesgos: 'riesg res obj gral',
//             polymorphic_ctype: 34,
//             objetivo_general: 6,
//             productos_res_og: [],
//           },
//         ],
//         objetivos_especificos_og: [
//           {
//             id: 5,
//             indicador_oe: [
//               {
//                 id: 30,
//                 codigo: 'IND001-SPO1',
//                 descripcion: 'Descripcion del Indicador IND001-SPO1',
//                 redaccion: 'GUIA',
//                 fuente_verificacion: 'Listas',
//                 target_poblacion: '100',
//                 fechaTargetPoblacion: '2025-09-18',
//                 tipo: 'A-Z',
//                 frecuencia: 'MENSUAL',
//                 responsable: '',
//                 baseline: '10',
//                 fechaLineaBase: null,
//                 target_q1: '',
//                 fechaTargetQ1: null,
//                 target_q2: '',
//                 fechaTargetQ2: null,
//                 target_q3: '',
//                 fechaTargetQ3: null,
//                 target_q4: null,
//                 fechaTargetQ4: null,
//                 polymorphic_ctype: 28,
//                 objetivo_especifico: 5,
//               },
//               {
//                 id: 31,
//                 codigo: 'IND00-SPO',
//                 descripcion: 'Descripcion',
//                 redaccion: 'GUIA',
//                 fuente_verificacion: '',
//                 target_poblacion: '',
//                 fechaTargetPoblacion: null,
//                 tipo: 'A-Z',
//                 frecuencia: 'MENSUAL',
//                 responsable: '',
//                 baseline: '',
//                 fechaLineaBase: null,
//                 target_q1: '',
//                 fechaTargetQ1: null,
//                 target_q2: '',
//                 fechaTargetQ2: null,
//                 target_q3: '',
//                 fechaTargetQ3: null,
//                 target_q4: null,
//                 fechaTargetQ4: null,
//                 polymorphic_ctype: 28,
//                 objetivo_especifico: 5,
//               },
//             ],
//             resultados_oe: [
//               {
//                 id: 8,
//                 indicador_res_oe: [
//                   {
//                     id: 29,
//                     codigo: 'IND00-RES00-SPO',
//                     descripcion: '',
//                     redaccion: 'GUIA',
//                     fuente_verificacion: '',
//                     target_poblacion: '',
//                     fechaTargetPoblacion: null,
//                     tipo: 'A-Z',
//                     frecuencia: 'MENSUAL',
//                     responsable: null,
//                     baseline: '',
//                     fechaLineaBase: null,
//                     target_q1: '',
//                     fechaTargetQ1: null,
//                     target_q2: '',
//                     fechaTargetQ2: null,
//                     target_q3: '',
//                     fechaTargetQ3: null,
//                     target_q4: null,
//                     fechaTargetQ4: null,
//                     polymorphic_ctype: 33,
//                     resultado_obj_especifico: 8,
//                   },
//                 ],
//                 productos_res_oe: [],
//                 proceso_resultado_oe: [],
//                 actividad_resultado_oe: [],
//                 codigo: 'RES002-SPO1',
//                 descripcion: 'Descripcion de RES002-SPO1',
//                 supuestos: 'SUp Res OE',
//                 riesgos: 'Riesg Res OE',
//                 polymorphic_ctype: 31,
//                 objetivo_especifico: 5,
//               },
//               {
//                 id: 9,
//                 indicador_res_oe: [],
//                 productos_res_oe: [],
//                 proceso_resultado_oe: [],
//                 actividad_resultado_oe: [],
//                 codigo: 'RES001-SPO1',
//                 descripcion: 'Descripcion del resultado RES001-SPO1',
//                 supuestos: 'SUp Res OE',
//                 riesgos: 'Riesg Res OE',
//                 polymorphic_ctype: 31,
//                 objetivo_especifico: 5,
//               },
//               {
//                 id: 10,
//                 indicador_res_oe: [],
//                 productos_res_oe: [
//                   {
//                     id: 4,
//                     codigo: 'PROD002-RES01-SPO1',
//                     descripcion: 'PROD002-RES01-SPO1',
//                     supuestos: 'sup prod',
//                     riesgos: 'risk prod',
//                     entregado: false,
//                     polymorphic_ctype: 32,
//                     objetivo_especifico: null,
//                   },
//                   {
//                     id: 5,
//                     codigo: 'PROD001-RES01-SPO1',
//                     descripcion: 'Descricipn  PROD001-RES01-SPO1',
//                     supuestos: 'sup prod',
//                     riesgos: 'risk prod',
//                     entregado: false,
//                     polymorphic_ctype: 32,
//                     objetivo_especifico: null,
//                   },
//                 ],
//                 proceso_resultado_oe: [
//                   {
//                     id: 5,
//                     actividades: [],
//                     codigo: 'PROC001-RES003-SP01',
//                     titulo: 'Proceso Resultado OE',
//                     descripcion: '',
//                     resultado_og: null,
//                     resultado_oe: 10,
//                     producto_oe: null,
//                   },
//                 ],
//                 actividad_resultado_oe: [],
//                 codigo: 'RES003-SPO1',
//                 descripcion: 'Des Res OE RES01-SPO1',
//                 supuestos: 'SUp Res OE',
//                 riesgos: 'Riesg Res OE',
//                 polymorphic_ctype: 31,
//                 objetivo_especifico: 5,
//               },
//             ],
//             productos_oe: [
//               {
//                 id: 3,
//                 proceso_producto_oe: [],
//                 actividad_producto_oe: [],
//                 codigo: 'P001-SO1',
//                 descripcion: 'Descripcion de P001-SO1',
//                 supuestos: 'sup prod oe',
//                 riesgos: 'risk oe',
//                 entregado: false,
//                 polymorphic_ctype: 30,
//                 objetivo_especifico: 5,
//               },
//             ],
//             codigo: 'SPO1',
//             descripcion: 'Descripcion del Objetivo Especifico SPO1',
//             supuestos: 'Sup',
//             riesgos: 'Riesgos',
//             proyecto: null,
//             objetivo_general: 6,
//           },
//         ],
//         codigo: 'OO',
//         descripcion: 'Objetivo General',
//         supuestos: 'Sup R',
//         riesgos: 'ries og',
//         proyecto: 6,
//       },
//     },
//     indicadorog: [
//       {
//         tipo: 'indicadorog',
//         data: {
//           id: 27,
//           codigo: 'IND002-OG',
//           descripcion: 'IND002-OG',
//           redaccion: 'SMART',
//           fuente_verificacion: 'Fuentes de verificacion',
//           target_poblacion: '50',
//           fechaTargetPoblacion: '2025-11-09',
//           tipo: 'A-Z',
//           frecuencia: 'MENSUAL',
//           responsable: null,
//           baseline: '0',
//           fechaLineaBase: '2025-09-11',
//           target_q1: '',
//           fechaTargetQ1: null,
//           target_q2: '',
//           fechaTargetQ2: null,
//           target_q3: '',
//           fechaTargetQ3: null,
//           target_q4: null,
//           fechaTargetQ4: null,
//           polymorphic_ctype: 29,
//           objetivo_general: 6,
//         },
//       },
//       {
//         tipo: 'indicadorog',
//         data: {
//           id: 28,
//           codigo: 'IND0001-OG',
//           descripcion: 'Descripcion del IND0001-OG',
//           redaccion: 'SMART',
//           fuente_verificacion: 'Fuentes de verificacion',
//           target_poblacion: '100',
//           fechaTargetPoblacion: '2025-11-09',
//           tipo: '1-9',
//           frecuencia: 'CUATRIMESTRAL',
//           responsable: null,
//           baseline: '10',
//           fechaLineaBase: '2025-09-01',
//           target_q1: '30',
//           fechaTargetQ1: '2025-09-17',
//           target_q2: '40',
//           fechaTargetQ2: '2025-10-01',
//           target_q3: '50',
//           fechaTargetQ3: '2025-10-08',
//           target_q4: null,
//           fechaTargetQ4: null,
//           polymorphic_ctype: 29,
//           objetivo_general: 6,
//         },
//       },
//     ],
//     resultadoog: {
//       tipo: 'resultadoog',
//       data: {
//         id: 11,
//         indicador_res_og: [],
//         proceso_resultado_og: [
//           {
//             id: 6,
//             actividades: [],
//             codigo: 'PROC001-R01-OO',
//             titulo: 'Procesos Res OG',
//             descripcion: '',
//             resultado_og: 11,
//             resultado_oe: null,
//             producto_oe: null,
//           },
//         ],
//         actividad_resultado_og: [],
//         codigo: 'R01-OO',
//         descripcion: 'Descripcion del resultado de obj gral',
//         supuestos: 'sup res obj gral',
//         riesgos: 'riesg res obj gral',
//         polymorphic_ctype: 34,
//         objetivo_general: 6,
//         productos_res_og: [],
//       },
//     },
//     procesorog: {
//       tipo: 'procesorog',
//       data: {
//         id: 6,
//         actividades: [],
//         codigo: 'PROC001-R01-OO',
//         titulo: 'Procesos Res OG',
//         descripcion: '',
//         resultado_og: 11,
//         resultado_oe: null,
//         producto_oe: null,
//       },
//     },
//   },
//   nodosRelacionados: [
//     {
//       id: '2',
//       type: 'objetivogeneral',
//       dimensions: {
//         width: 700,
//         height: 210,
//       },
//       computedPosition: {
//         x: 1500,
//         y: 650,
//         z: 0,
//       },
//       handleBounds: {
//         source: [
//           {
//             id: 'source-2',
//             type: 'source',
//             nodeId: '2',
//             position: 'bottom',
//             x: 343.9998675347262,
//             y: 203.75002305343523,
//             width: 12,
//             height: 12,
//           },
//         ],
//         target: [
//           {
//             id: 'source-2',
//             type: 'target',
//             nodeId: '2',
//             position: 'top',
//             x: 343.9998675347262,
//             y: -5.999910933111628,
//             width: 12,
//             height: 12,
//           },
//         ],
//       },
//       selected: false,
//       dragging: false,
//       resizing: false,
//       initialized: false,
//       isParent: false,
//       position: {
//         x: 1500,
//         y: 650,
//       },
//       data: {
//         label: 'Objetivo General',
//         type: 'objetivogeneral',
//         estado: 'ES',
//         mapaNodoId: '6',
//         nodoProyecto: {
//           id: 6,
//           codigo: 'OO',
//           descripcion: 'Objetivo General',
//           supuestos: 'Sup R',
//           riesgos: 'ries og',
//           proyecto: 6,
//         },
//       },
//       events: {},
//     },
//     {
//       id: '3',
//       type: 'indicadorog',
//       dimensions: {
//         width: 700,
//         height: 513,
//       },
//       computedPosition: {
//         x: 375,
//         y: 1300,
//         z: 0,
//       },
//       handleBounds: {
//         source: [
//           {
//             id: 'source-3',
//             type: 'source',
//             nodeId: '3',
//             position: 'bottom',
//             x: 343.99992869091056,
//             y: 506.93755559439626,
//             width: 12,
//             height: 12,
//           },
//         ],
//         target: [
//           {
//             id: 'source-3',
//             type: 'target',
//             nodeId: '3',
//             position: 'top',
//             x: 343.99992869091056,
//             y: -5.999910933111628,
//             width: 12,
//             height: 12,
//           },
//         ],
//       },
//       selected: false,
//       dragging: false,
//       resizing: false,
//       initialized: false,
//       isParent: false,
//       position: {
//         x: 375,
//         y: 1300,
//       },
//       data: {
//         label: 'Indicador OG',
//         type: 'indicadorog',
//         estado: 'ES',
//         mapaNodoId: '6',
//         nodoProyecto: {
//           id: 27,
//           codigo: 'IND002-OG',
//           descripcion: 'IND002-OG',
//           definicion: 'Definicion del indicador',
//           redaccion: 'SMART',
//           fuente_verificacion: 'Fuentes de verificacion',
//           target_poblacion: '50',
//           fechaTargetPoblacion: '2025-11-09',
//           tipo: 'A-Z',
//           frecuencia: 'MENSUAL',
//           responsable: null,
//           baseline: '0',
//           fechaLineaBase: '2025-09-11',
//           target_q1: '',
//           fechaTargetQ1: null,
//           target_q2: '',
//           fechaTargetQ2: null,
//           target_q3: '',
//           fechaTargetQ3: null,
//           objetivo_general: 6,
//         },
//       },
//       events: {},
//     },
//     {
//       id: '4',
//       type: 'indicadorog',
//       dimensions: {
//         width: 700,
//         height: 513,
//       },
//       computedPosition: {
//         x: 1125,
//         y: 1300,
//         z: 0,
//       },
//       handleBounds: {
//         source: [
//           {
//             id: 'source-4',
//             type: 'source',
//             nodeId: '4',
//             position: 'bottom',
//             x: 343.99998984709487,
//             y: 506.93755559439626,
//             width: 12,
//             height: 12,
//           },
//         ],
//         target: [
//           {
//             id: 'source-4',
//             type: 'target',
//             nodeId: '4',
//             position: 'top',
//             x: 343.99998984709487,
//             y: -5.999910933111628,
//             width: 12,
//             height: 12,
//           },
//         ],
//       },
//       selected: false,
//       dragging: false,
//       resizing: false,
//       initialized: false,
//       isParent: false,
//       position: {
//         x: 1125,
//         y: 1300,
//       },
//       data: {
//         label: 'Indicador OG',
//         type: 'indicadorog',
//         estado: 'ES',
//         mapaNodoId: '6',
//         nodoProyecto: {
//           id: 28,
//           codigo: 'IND0001-OG',
//           descripcion: 'Descripcion del IND0001-OG',
//           redaccion: 'SMART',
//           fuente_verificacion: 'Fuentes de verificacion',
//           target_poblacion: '100',
//           fechaTargetPoblacion: '2025-11-09',
//           tipo: '1-9',
//           frecuencia: 'CUATRIMESTRAL',
//           responsable: null,
//           baseline: '10',
//           fechaLineaBase: '2025-09-01',
//           target_q1: '30',
//           fechaTargetQ1: '2025-09-17',
//           target_q2: '40',
//           fechaTargetQ2: '2025-10-01',
//           target_q3: '50',
//           fechaTargetQ3: '2025-10-08',
//           objetivo_general: 6,
//         },
//       },
//       events: {},
//     },
//     {
//       id: '16',
//       type: 'resultadoog',
//       dimensions: {
//         width: 700,
//         height: 210,
//       },
//       computedPosition: {
//         x: 4500,
//         y: 1300,
//         z: 0,
//       },
//       handleBounds: {
//         source: [
//           {
//             id: 'source-16',
//             type: 'source',
//             nodeId: '16',
//             position: 'bottom',
//             x: 344.0001121594636,
//             y: 203.75002305343523,
//             width: 12,
//             height: 12,
//           },
//         ],
//         target: [
//           {
//             id: 'source-16',
//             type: 'target',
//             nodeId: '16',
//             position: 'top',
//             x: 344.0001121594636,
//             y: -5.999910933111628,
//             width: 12,
//             height: 12,
//           },
//         ],
//       },
//       selected: false,
//       dragging: false,
//       resizing: false,
//       initialized: false,
//       isParent: false,
//       position: {
//         x: 4500,
//         y: 1300,
//       },
//       data: {
//         label: 'Resultado OG',
//         type: 'resultadoog',
//         mapaNodoId: '6',
//         nodoProyecto: {
//           id: 11,
//           codigo: 'R01-OO',
//           descripcion: 'Descripcion del resultado de obj gral',
//           supuestos: 'sup res obj gral',
//           riesgos: 'riesg res obj gral',
//           objetivo_general: 6,
//         },
//       },
//       events: {},
//     },
//     {
//       id: '17',
//       type: 'procesorog',
//       dimensions: {
//         width: 700,
//         height: 200,
//       },
//       computedPosition: {
//         x: 4500,
//         y: 1950,
//         z: 0,
//       },
//       handleBounds: {
//         source: [
//           {
//             id: 'source-17',
//             type: 'source',
//             nodeId: '17',
//             position: 'bottom',
//             x: 344.0001121594636,
//             y: 193.99989258429932,
//             width: 12,
//             height: 12,
//           },
//         ],
//         target: [
//           {
//             id: 'source-17',
//             type: 'target',
//             nodeId: '17',
//             position: 'top',
//             x: 344.0001121594636,
//             y: -6.0001555578489825,
//             width: 12,
//             height: 12,
//           },
//         ],
//       },
//       selected: false,
//       dragging: false,
//       resizing: false,
//       initialized: false,
//       isParent: false,
//       position: {
//         x: 4500,
//         y: 1950,
//       },
//       data: {
//         label: 'Procesos Resultado OG',
//         type: 'procesorog',
//         mapaNodoId: '6',
//         nodoProyecto: {
//           id: 6,
//           codigo: 'PROC001-R01-OO',
//           titulo: 'Procesos Res OG',
//           descripcion: '',
//           resultado_og: 11,
//           resultado_oe: null,
//         },
//       },
//       events: {},
//     },
//   ],
//   seleccionesSimples: {
//     objetivoGeneralId: 6,
//     indicadorOGIds: [27, 28],
//     resultadoOGId: 11,
//     procesoOGId: 6,
//   },
// })

/*const estructuraProcedencia = ref({
  datosProcedencia: {
    objetivogeneral: {
      tipo: 'objetivogeneral',
      data: {
        id: 6,
        kpis: [],
        indicador_og: [
          {
            id: 27,
            codigo: 'IND002-OG',
            descripcion: 'IND002-OG',
            redaccion: 'SMART',
            fuente_verificacion: 'Fuentes de verificacion',
            target_poblacion: '50',
            fechaTargetPoblacion: '2025-11-09',
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: null,
            baseline: '0',
            fechaLineaBase: '2025-09-11',
            target_q1: '',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 29,
            objetivo_general: 6,
          },
          {
            id: 28,
            codigo: 'IND0001-OG',
            descripcion: 'Descripcion del IND0001-OG',
            redaccion: 'SMART',
            fuente_verificacion: 'Fuentes de verificacion',
            target_poblacion: '100',
            fechaTargetPoblacion: '2025-11-09',
            tipo: '1-9',
            frecuencia: 'CUATRIMESTRAL',
            responsable: null,
            baseline: '10',
            fechaLineaBase: '2025-09-01',
            target_q1: '30',
            fechaTargetQ1: '2025-09-17',
            target_q2: '40',
            fechaTargetQ2: '2025-10-01',
            target_q3: '50',
            fechaTargetQ3: '2025-10-08',
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 29,
            objetivo_general: 6,
          },
        ],
        resultados_og: [
          {
            id: 11,
            indicador_res_og: [],
            proceso_resultado_og: [
              {
                id: 6,
                actividades: [],
                codigo: 'PROC001-R01-OO',
                titulo: 'Procesos Res OG',
                descripcion: '',
                resultado_og: 11,
                resultado_oe: null,
                producto_oe: null,
              },
            ],
            actividad_resultado_og: [],
            codigo: 'R01-OO',
            descripcion: 'Descripcion del resultado de obj gral',
            supuestos: 'sup res obj gral',
            riesgos: 'riesg res obj gral',
            polymorphic_ctype: 34,
            objetivo_general: 6,
            productos_res_og: [],
          },
        ],
        objetivos_especificos_og: [
          {
            id: 5,
            indicador_oe: [
              {
                id: 30,
                codigo: 'IND001-SPO1',
                descripcion: 'Descripcion del Indicador IND001-SPO1',
                redaccion: 'GUIA',
                fuente_verificacion: 'Listas',
                target_poblacion: '100',
                fechaTargetPoblacion: '2025-09-18',
                tipo: 'A-Z',
                frecuencia: 'MENSUAL',
                responsable: '',
                baseline: '10',
                fechaLineaBase: null,
                target_q1: '',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 28,
                objetivo_especifico: 5,
              },
              {
                id: 31,
                codigo: 'IND00-SPO',
                descripcion: 'Descripcion',
                redaccion: 'GUIA',
                fuente_verificacion: '',
                target_poblacion: '',
                fechaTargetPoblacion: null,
                tipo: 'A-Z',
                frecuencia: 'MENSUAL',
                responsable: '',
                baseline: '',
                fechaLineaBase: null,
                target_q1: '',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 28,
                objetivo_especifico: 5,
              },
            ],
            resultados_oe: [
              {
                id: 8,
                indicador_res_oe: [
                  {
                    id: 29,
                    codigo: 'IND00-RES00-SPO',
                    descripcion: '',
                    redaccion: 'GUIA',
                    fuente_verificacion: '',
                    target_poblacion: '',
                    fechaTargetPoblacion: null,
                    tipo: 'A-Z',
                    frecuencia: 'MENSUAL',
                    responsable: null,
                    baseline: '',
                    fechaLineaBase: null,
                    target_q1: '',
                    fechaTargetQ1: null,
                    target_q2: '',
                    fechaTargetQ2: null,
                    target_q3: '',
                    fechaTargetQ3: null,
                    target_q4: null,
                    fechaTargetQ4: null,
                    polymorphic_ctype: 33,
                    resultado_obj_especifico: 8,
                  },
                ],
                productos_res_oe: [],
                proceso_resultado_oe: [],
                actividad_resultado_oe: [],
                codigo: 'RES002-SPO1',
                descripcion: 'Descripcion de RES002-SPO1',
                supuestos: 'SUp Res OE',
                riesgos: 'Riesg Res OE',
                polymorphic_ctype: 31,
                objetivo_especifico: 5,
              },
              {
                id: 9,
                indicador_res_oe: [],
                productos_res_oe: [],
                proceso_resultado_oe: [],
                actividad_resultado_oe: [],
                codigo: 'RES001-SPO1',
                descripcion: 'Descripcion del resultado RES001-SPO1',
                supuestos: 'SUp Res OE',
                riesgos: 'Riesg Res OE',
                polymorphic_ctype: 31,
                objetivo_especifico: 5,
              },
              {
                id: 10,
                indicador_res_oe: [],
                productos_res_oe: [
                  {
                    id: 4,
                    codigo: 'PROD002-RES01-SPO1',
                    descripcion: 'PROD002-RES01-SPO1',
                    supuestos: 'sup prod',
                    riesgos: 'risk prod',
                    entregado: false,
                    polymorphic_ctype: 32,
                    objetivo_especifico: null,
                  },
                  {
                    id: 5,
                    codigo: 'PROD001-RES01-SPO1',
                    descripcion: 'Descricipn  PROD001-RES01-SPO1',
                    supuestos: 'sup prod',
                    riesgos: 'risk prod',
                    entregado: false,
                    polymorphic_ctype: 32,
                    objetivo_especifico: null,
                  },
                ],
                proceso_resultado_oe: [
                  {
                    id: 5,
                    actividades: [],
                    codigo: 'PROC001-RES003-SP01',
                    titulo: 'Proceso Resultado OE',
                    descripcion: '',
                    resultado_og: null,
                    resultado_oe: 10,
                    producto_oe: null,
                  },
                ],
                actividad_resultado_oe: [],
                codigo: 'RES003-SPO1',
                descripcion: 'Des Res OE RES01-SPO1',
                supuestos: 'SUp Res OE',
                riesgos: 'Riesg Res OE',
                polymorphic_ctype: 31,
                objetivo_especifico: 5,
              },
            ],
            productos_oe: [
              {
                id: 3,
                proceso_producto_oe: [],
                actividad_producto_oe: [],
                codigo: 'P001-SO1',
                descripcion: 'Descripcion de P001-SO1',
                supuestos: 'sup prod oe',
                riesgos: 'risk oe',
                entregado: false,
                polymorphic_ctype: 30,
                objetivo_especifico: 5,
              },
            ],
            codigo: 'SPO1',
            descripcion: 'Descripcion del Objetivo Especifico SPO1',
            supuestos: 'Sup',
            riesgos: 'Riesgos',
            proyecto: null,
            objetivo_general: 6,
          },
        ],
        codigo: 'OO',
        descripcion: 'Objetivo General',
        supuestos: 'Sup R',
        riesgos: 'ries og',
        proyecto: 6,
      },
    },
    indicadorog: [
      {
        tipo: 'indicadorog',
        data: {
          id: 28,
          codigo: 'IND0001-OG',
          descripcion: 'Descripcion del IND0001-OG',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '100',
          fechaTargetPoblacion: '2025-11-09',
          tipo: '1-9',
          frecuencia: 'CUATRIMESTRAL',
          responsable: null,
          baseline: '10',
          fechaLineaBase: '2025-09-01',
          target_q1: '30',
          fechaTargetQ1: '2025-09-17',
          target_q2: '40',
          fechaTargetQ2: '2025-10-01',
          target_q3: '50',
          fechaTargetQ3: '2025-10-08',
          target_q4: null,
          fechaTargetQ4: null,
          polymorphic_ctype: 29,
          objetivo_general: 6,
        },
      },
      {
        tipo: 'indicadorog',
        data: {
          id: 27,
          codigo: 'IND002-OG',
          descripcion: 'IND002-OG',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '50',
          fechaTargetPoblacion: '2025-11-09',
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: null,
          baseline: '0',
          fechaLineaBase: '2025-09-11',
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          target_q4: null,
          fechaTargetQ4: null,
          polymorphic_ctype: 29,
          objetivo_general: 6,
        },
      },
    ],
    objetivoespecificoog: {
      tipo: 'objetivoespecificoog',
      data: {
        id: 5,
        indicador_oe: [
          {
            id: 30,
            codigo: 'IND001-SPO1',
            descripcion: 'Descripcion del Indicador IND001-SPO1',
            redaccion: 'GUIA',
            fuente_verificacion: 'Listas',
            target_poblacion: '100',
            fechaTargetPoblacion: '2025-09-18',
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: '',
            baseline: '10',
            fechaLineaBase: null,
            target_q1: '',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 28,
            objetivo_especifico: 5,
          },
          {
            id: 31,
            codigo: 'IND00-SPO',
            descripcion: 'Descripcion',
            redaccion: 'GUIA',
            fuente_verificacion: '',
            target_poblacion: '',
            fechaTargetPoblacion: null,
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: '',
            baseline: '',
            fechaLineaBase: null,
            target_q1: '',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 28,
            objetivo_especifico: 5,
          },
        ],
        resultados_oe: [
          {
            id: 8,
            indicador_res_oe: [
              {
                id: 29,
                codigo: 'IND00-RES00-SPO',
                descripcion: '',
                redaccion: 'GUIA',
                fuente_verificacion: '',
                target_poblacion: '',
                fechaTargetPoblacion: null,
                tipo: 'A-Z',
                frecuencia: 'MENSUAL',
                responsable: null,
                baseline: '',
                fechaLineaBase: null,
                target_q1: '',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 33,
                resultado_obj_especifico: 8,
              },
            ],
            productos_res_oe: [],
            proceso_resultado_oe: [],
            actividad_resultado_oe: [],
            codigo: 'RES002-SPO1',
            descripcion: 'Descripcion de RES002-SPO1',
            supuestos: 'SUp Res OE',
            riesgos: 'Riesg Res OE',
            polymorphic_ctype: 31,
            objetivo_especifico: 5,
          },
          {
            id: 9,
            indicador_res_oe: [],
            productos_res_oe: [],
            proceso_resultado_oe: [],
            actividad_resultado_oe: [],
            codigo: 'RES001-SPO1',
            descripcion: 'Descripcion del resultado RES001-SPO1',
            supuestos: 'SUp Res OE',
            riesgos: 'Riesg Res OE',
            polymorphic_ctype: 31,
            objetivo_especifico: 5,
          },
          {
            id: 10,
            indicador_res_oe: [],
            productos_res_oe: [
              {
                id: 4,
                codigo: 'PROD002-RES01-SPO1',
                descripcion: 'PROD002-RES01-SPO1',
                supuestos: 'sup prod',
                riesgos: 'risk prod',
                entregado: false,
                polymorphic_ctype: 32,
                objetivo_especifico: null,
              },
              {
                id: 5,
                codigo: 'PROD001-RES01-SPO1',
                descripcion: 'Descricipn  PROD001-RES01-SPO1',
                supuestos: 'sup prod',
                riesgos: 'risk prod',
                entregado: false,
                polymorphic_ctype: 32,
                objetivo_especifico: null,
              },
            ],
            proceso_resultado_oe: [
              {
                id: 5,
                actividades: [],
                codigo: 'PROC001-RES003-SP01',
                titulo: 'Proceso Resultado OE',
                descripcion: '',
                resultado_og: null,
                resultado_oe: 10,
                producto_oe: null,
              },
            ],
            actividad_resultado_oe: [],
            codigo: 'RES003-SPO1',
            descripcion: 'Des Res OE RES01-SPO1',
            supuestos: 'SUp Res OE',
            riesgos: 'Riesg Res OE',
            polymorphic_ctype: 31,
            objetivo_especifico: 5,
          },
        ],
        productos_oe: [
          {
            id: 3,
            proceso_producto_oe: [],
            actividad_producto_oe: [],
            codigo: 'P001-SO1',
            descripcion: 'Descripcion de P001-SO1',
            supuestos: 'sup prod oe',
            riesgos: 'risk oe',
            entregado: false,
            polymorphic_ctype: 30,
            objetivo_especifico: 5,
          },
        ],
        codigo: 'SPO1',
        descripcion: 'Descripcion del Objetivo Especifico SPO1',
        supuestos: 'Sup',
        riesgos: 'Riesgos',
        proyecto: null,
        objetivo_general: 6,
      },
    },
    indicadoroe: {
      tipo: 'indicadoroe',
      data: {
        id: 30,
        codigo: 'IND001-SPO1',
        descripcion: 'Descripcion del Indicador IND001-SPO1',
        redaccion: 'GUIA',
        fuente_verificacion: 'Listas',
        target_poblacion: '100',
        fechaTargetPoblacion: '2025-09-18',
        tipo: 'A-Z',
        frecuencia: 'MENSUAL',
        responsable: '',
        baseline: '10',
        fechaLineaBase: null,
        target_q1: '',
        fechaTargetQ1: null,
        target_q2: '',
        fechaTargetQ2: null,
        target_q3: '',
        fechaTargetQ3: null,
        target_q4: null,
        fechaTargetQ4: null,
        polymorphic_ctype: 28,
        objetivo_especifico: 5,
      },
    },
    resultadooe: {
      tipo: 'resultadooe',
      data: {
        id: 10,
        indicador_res_oe: [],
        productos_res_oe: [
          {
            id: 4,
            codigo: 'PROD002-RES01-SPO1',
            descripcion: 'PROD002-RES01-SPO1',
            supuestos: 'sup prod',
            riesgos: 'risk prod',
            entregado: false,
            polymorphic_ctype: 32,
            objetivo_especifico: null,
          },
          {
            id: 5,
            codigo: 'PROD001-RES01-SPO1',
            descripcion: 'Descricipn  PROD001-RES01-SPO1',
            supuestos: 'sup prod',
            riesgos: 'risk prod',
            entregado: false,
            polymorphic_ctype: 32,
            objetivo_especifico: null,
          },
        ],
        proceso_resultado_oe: [
          {
            id: 5,
            actividades: [],
            codigo: 'PROC001-RES003-SP01',
            titulo: 'Proceso Resultado OE',
            descripcion: '',
            resultado_og: null,
            resultado_oe: 10,
            producto_oe: null,
          },
        ],
        actividad_resultado_oe: [],
        codigo: 'RES003-SPO1',
        descripcion: 'Des Res OE RES01-SPO1',
        supuestos: 'SUp Res OE',
        riesgos: 'Riesg Res OE',
        polymorphic_ctype: 31,
        objetivo_especifico: 5,
      },
    },
    procesoroe: {
      tipo: 'procesoroe',
      data: {
        id: 5,
        actividades: [],
        codigo: 'PROC001-RES003-SP01',
        titulo: 'Proceso Resultado OE',
        descripcion: '',
        resultado_og: null,
        resultado_oe: 10,
        producto_oe: null,
      },
    },
    productooe: {
      tipo: 'productooe',
      data: {
        id: 3,
        proceso_producto_oe: [],
        actividad_producto_oe: [],
        codigo: 'P001-SO1',
        descripcion: 'Descripcion de P001-SO1',
        supuestos: 'sup prod oe',
        riesgos: 'risk oe',
        entregado: false,
        polymorphic_ctype: 30,
        objetivo_especifico: 5,
      },
    },
  },
  nodosRelacionados: [
    {
      id: '2',
      type: 'objetivogeneral',
      dimensions: {
        width: 700,
        height: 210,
      },
      computedPosition: {
        x: 1500,
        y: 650,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-2',
            type: 'source',
            nodeId: '2',
            position: 'bottom',
            x: 343.9998675347262,
            y: 203.75002305343523,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-2',
            type: 'target',
            nodeId: '2',
            position: 'top',
            x: 343.9998675347262,
            y: -5.999910933111628,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1500,
        y: 650,
      },
      data: {
        label: 'Objetivo General',
        type: 'objetivogeneral',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 6,
          codigo: 'OO',
          descripcion: 'Objetivo General',
          supuestos: 'Sup R',
          riesgos: 'ries og',
          proyecto: 6,
        },
      },
      events: {},
    },
    {
      id: '4',
      type: 'indicadorog',
      dimensions: {
        width: 700,
        height: 513,
      },
      computedPosition: {
        x: 1125,
        y: 1300,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-4',
            type: 'source',
            nodeId: '4',
            position: 'bottom',
            x: 343.99998984709487,
            y: 506.93755559439626,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-4',
            type: 'target',
            nodeId: '4',
            position: 'top',
            x: 343.99998984709487,
            y: -5.999910933111628,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1125,
        y: 1300,
      },
      data: {
        label: 'Indicador OG',
        type: 'indicadorog',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 28,
          codigo: 'IND0001-OG',
          descripcion: 'Descripcion del IND0001-OG',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '100',
          fechaTargetPoblacion: '2025-11-09',
          tipo: '1-9',
          frecuencia: 'CUATRIMESTRAL',
          responsable: null,
          baseline: '10',
          fechaLineaBase: '2025-09-01',
          target_q1: '30',
          fechaTargetQ1: '2025-09-17',
          target_q2: '40',
          fechaTargetQ2: '2025-10-01',
          target_q3: '50',
          fechaTargetQ3: '2025-10-08',
          objetivo_general: 6,
        },
      },
      events: {},
    },
    {
      id: '3',
      type: 'indicadorog',
      dimensions: {
        width: 700,
        height: 513,
      },
      computedPosition: {
        x: 375,
        y: 1300,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-3',
            type: 'source',
            nodeId: '3',
            position: 'bottom',
            x: 343.99992869091056,
            y: 506.93755559439626,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-3',
            type: 'target',
            nodeId: '3',
            position: 'top',
            x: 343.99992869091056,
            y: -5.999910933111628,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 375,
        y: 1300,
      },
      data: {
        label: 'Indicador OG',
        type: 'indicadorog',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 27,
          codigo: 'IND002-OG',
          descripcion: 'IND002-OG',
          definicion: 'Definicion del indicador',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '50',
          fechaTargetPoblacion: '2025-11-09',
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: null,
          baseline: '0',
          fechaLineaBase: '2025-09-11',
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          objetivo_general: 6,
        },
      },
      events: {},
    },
    {
      id: '5',
      type: 'objetivoespecificoog',
      dimensions: {
        width: 700,
        height: 210,
      },
      computedPosition: {
        x: 1875,
        y: 1300,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-5',
            type: 'source',
            nodeId: '5',
            position: 'bottom',
            x: 343.99998984709487,
            y: 203.75002305343523,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-5',
            type: 'target',
            nodeId: '5',
            position: 'top',
            x: 343.99998984709487,
            y: -5.999910933111628,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1875,
        y: 1300,
      },
      data: {
        label: 'Objetivo Especifico OG',
        type: 'objetivoespecificoog',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 5,
          codigo: 'SPO1',
          descripcion: 'Descripcion del Objetivo Especifico SPO1',
          supuestos: 'Sup',
          riesgos: 'Riesgos',
          proyecto: null,
          objetivo_general: 6,
        },
      },
      events: {},
    },
    {
      id: '9',
      type: 'indicadoroe',
      dimensions: {
        width: 700,
        height: 513,
      },
      computedPosition: {
        x: 1500,
        y: 1950,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-9',
            type: 'source',
            nodeId: '9',
            position: 'bottom',
            x: 343.9998675347262,
            y: 506.93731096965894,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-9',
            type: 'target',
            nodeId: '9',
            position: 'top',
            x: 343.9998675347262,
            y: -6.0001555578489825,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1500,
        y: 1950,
      },
      data: {
        label: 'Indicador OE',
        type: 'indicadoroe',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 30,
          codigo: 'IND001-SPO1',
          descripcion: 'Descripcion del Indicador IND001-SPO1',
          redaccion: 'GUIA',
          fuente_verificacion: 'Listas',
          target_poblacion: '100',
          fechaTargetPoblacion: '2025-09-18',
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: '',
          baseline: '10',
          fechaLineaBase: null,
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          objetivo_especifico: 5,
        },
      },
      events: {},
    },
    {
      id: '10',
      type: 'resultadooe',
      dimensions: {
        width: 700,
        height: 210,
      },
      computedPosition: {
        x: 2268.6414182242056,
        y: 2063.2824645932506,
        z: 1000,
      },
      handleBounds: {
        source: [
          {
            id: 'source-10',
            type: 'source',
            nodeId: '10',
            position: 'bottom',
            x: 344.0001121594636,
            y: 203.74990074106657,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-10',
            type: 'target',
            nodeId: '10',
            position: 'top',
            x: 344.0001121594636,
            y: -6.0001555578489825,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: true,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 2268.6414182242056,
        y: 2063.2824645932506,
      },
      data: {
        label: 'Resultado OE',
        type: 'resultadooe',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 10,
          codigo: 'RES003-SPO1',
          descripcion: 'Des Res OE RES01-SPO1',
          supuestos: 'SUp Res OE',
          riesgos: 'Riesg Res OE',
          proceso: null,
          objetivo_especifico: 5,
        },
      },
      events: {},
    },
    {
      id: '14',
      type: 'procesoroe',
      dimensions: {
        width: 700,
        height: 200,
      },
      computedPosition: {
        x: 2250,
        y: 2600,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-14',
            type: 'source',
            nodeId: '14',
            position: 'bottom',
            x: 344.0001121594636,
            y: 194.00013720903667,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-14',
            type: 'target',
            nodeId: '14',
            position: 'top',
            x: 344.0001121594636,
            y: -5.999910933111628,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 2250,
        y: 2600,
      },
      data: {
        label: 'Procesos Resultado OE',
        type: 'procesoroe',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 5,
          codigo: 'PROC001-RES003-SP01',
          titulo: 'Proceso Resultado OE',
          descripcion: '',
          resultado_og: null,
          resultado_oe: 10,
        },
      },
      events: {},
    },
    {
      id: '11',
      type: 'productooe',
      dimensions: {
        width: 700,
        height: 234,
      },
      computedPosition: {
        x: 3000,
        y: 1950,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-11',
            type: 'source',
            nodeId: '11',
            position: 'bottom',
            x: 343.9998675347262,
            y: 227.68740979022485,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-11',
            type: 'target',
            nodeId: '11',
            position: 'top',
            x: 343.9998675347262,
            y: -6.0001555578489825,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 3000,
        y: 1950,
      },
      data: {
        label: 'Producto OE',
        type: 'productooe',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 3,
          codigo: 'P001-SO1',
          descripcion: 'Descripcion de P001-SO1',
          supuestos: 'sup prod oe',
          riesgos: 'risk oe',
          entregado: false,
          proceso: null,
          objetivo_especifico: 5,
        },
      },
      events: {},
    },
  ],
  seleccionesSimples: {
    objetivoGeneralId: 6,
    indicadorOGIds: [28, 27],
    objetivoEspecificoId: 5,
    indicadorOEId: 30,
    resultadoOEId: 10,
    procesoOEId: 5,
    productoOEId: 3,
  },
})*/
</script>

<style lang="scss" scoped></style>
