<template>
  <div>
    <h1>Notificaciones</h1>
    <!-- <indicador-line-chart></indicador-line-chart> -->
    <!-- Botón para abrir el modal -->
    <!-- <v-btn
      color="blue-darken-1"
      variant="elevated"
      block
      size="large"
      @click="modalAbierto = true"
      class="rounded-lg"
    >
      Abrir Registro de Bitácora
    </v-btn>
    <indicador-registro-bitacora
      v-model="modalAbierto"
      :idactividad="idactividad"
    ></indicador-registro-bitacora> -->

    <encabezado-contribucion :datos-estructura="estructuraProcedencia"></encabezado-contribucion>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import IndicadorLineChart from '@/modules/reportes/components/partials-indicador-registro/IndicadorLineChart.vue'
import IndicadorRegistroBitacora from '@/modules/reportes/components/IndicadorRegistroBitacora.vue'
import EncabezadoContribucion from '@/modules/formularios/components/EncabezadoContribucion.vue'

const idactividad = ref(15)

const modalAbierto = ref(false)

const estructuraProcedencia = ref({
  datosProcedencia: {
    objetivogeneral: {
      tipo: 'objetivogeneral',
      data: {
        id: 6,
        kpis: [],
        indicador_og: [
          {
            id: 27,
            codigo: 'IND002-OG',
            descripcion: 'IND002-OG',
            redaccion: 'SMART',
            fuente_verificacion: 'Fuentes de verificacion',
            target_poblacion: '50',
            fechaTargetPoblacion: '2025-11-09',
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: null,
            baseline: '0',
            fechaLineaBase: '2025-09-11',
            target_q1: '',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 29,
            objetivo_general: 6,
          },
          {
            id: 28,
            codigo: 'IND0001-OG',
            descripcion: 'Descripcion del IND0001-OG',
            redaccion: 'SMART',
            fuente_verificacion: 'Fuentes de verificacion',
            target_poblacion: '100',
            fechaTargetPoblacion: '2025-11-09',
            tipo: '1-9',
            frecuencia: 'CUATRIMESTRAL',
            responsable: null,
            baseline: '10',
            fechaLineaBase: '2025-09-01',
            target_q1: '30',
            fechaTargetQ1: '2025-09-17',
            target_q2: '40',
            fechaTargetQ2: '2025-10-01',
            target_q3: '50',
            fechaTargetQ3: '2025-10-08',
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 29,
            objetivo_general: 6,
          },
        ],
        resultados_og: [],
        objetivos_especificos_og: [
          {
            id: 5,
            indicador_oe: [
              {
                id: 30,
                codigo: 'IND001-SPO1',
                descripcion: 'Descripcion del Indicador IND001-SPO1',
                redaccion: 'GUIA',
                fuente_verificacion: 'Listas',
                target_poblacion: '100',
                fechaTargetPoblacion: '2025-09-18',
                tipo: 'A-Z',
                frecuencia: 'MENSUAL',
                responsable: '',
                baseline: '10',
                fechaLineaBase: null,
                target_q1: '',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 28,
                objetivo_especifico: 5,
              },
              {
                id: 31,
                codigo: 'IND00-SPO',
                descripcion: 'Descripcion',
                redaccion: 'GUIA',
                fuente_verificacion: '',
                target_poblacion: '',
                fechaTargetPoblacion: null,
                tipo: 'A-Z',
                frecuencia: 'MENSUAL',
                responsable: '',
                baseline: '',
                fechaLineaBase: null,
                target_q1: '',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 28,
                objetivo_especifico: 5,
              },
            ],
            resultados_oe: [
              {
                id: 8,
                indicador_res_oe: [
                  {
                    id: 29,
                    codigo: 'IND00-RES00-SPO',
                    descripcion: '',
                    redaccion: 'GUIA',
                    fuente_verificacion: '',
                    target_poblacion: '',
                    fechaTargetPoblacion: null,
                    tipo: 'A-Z',
                    frecuencia: 'MENSUAL',
                    responsable: null,
                    baseline: '',
                    fechaLineaBase: null,
                    target_q1: '',
                    fechaTargetQ1: null,
                    target_q2: '',
                    fechaTargetQ2: null,
                    target_q3: '',
                    fechaTargetQ3: null,
                    target_q4: null,
                    fechaTargetQ4: null,
                    polymorphic_ctype: 33,
                    resultado_obj_especifico: 8,
                  },
                ],
                productos_res_oe: [],
                proceso_resultado_oe: [],
                actividad_resultado_oe: [],
                codigo: 'RES002-SPO1',
                descripcion: 'Descripcion de RES002-SPO1',
                supuestos: 'SUp Res OE',
                riesgos: 'Riesg Res OE',
                polymorphic_ctype: 31,
                objetivo_especifico: 5,
              },
              {
                id: 9,
                indicador_res_oe: [],
                productos_res_oe: [],
                proceso_resultado_oe: [],
                actividad_resultado_oe: [],
                codigo: 'RES001-SPO1',
                descripcion: 'Descripcion del resultado RES001-SPO1',
                supuestos: 'SUp Res OE',
                riesgos: 'Riesg Res OE',
                polymorphic_ctype: 31,
                objetivo_especifico: 5,
              },
              {
                id: 10,
                indicador_res_oe: [],
                productos_res_oe: [
                  {
                    id: 4,
                    codigo: 'PROD002-RES01-SPO1',
                    descripcion: 'PROD002-RES01-SPO1',
                    supuestos: 'sup prod',
                    riesgos: 'risk prod',
                    entregado: false,
                    polymorphic_ctype: 32,
                    objetivo_especifico: null,
                  },
                  {
                    id: 5,
                    codigo: 'PROD001-RES01-SPO1',
                    descripcion: 'Descricipn  PROD001-RES01-SPO1',
                    supuestos: 'sup prod',
                    riesgos: 'risk prod',
                    entregado: false,
                    polymorphic_ctype: 32,
                    objetivo_especifico: null,
                  },
                ],
                proceso_resultado_oe: [
                  {
                    id: 5,
                    actividades: [],
                    codigo: 'PROC',
                    titulo: 'Proceso Resultado OE',
                    descripcion: '',
                    resultado_og: null,
                    resultado_oe: 10,
                    producto_oe: null,
                  },
                ],
                actividad_resultado_oe: [],
                codigo: 'RES003-SPO1',
                descripcion: 'Des Res OE RES01-SPO1',
                supuestos: 'SUp Res OE',
                riesgos: 'Riesg Res OE',
                polymorphic_ctype: 31,
                objetivo_especifico: 5,
              },
            ],
            productos_oe: [
              {
                id: 3,
                proceso_producto_oe: [],
                actividad_producto_oe: [],
                codigo: 'P001-SO1',
                descripcion: 'Descripcion de P001-SO1',
                supuestos: 'sup prod oe',
                riesgos: 'risk oe',
                entregado: false,
                polymorphic_ctype: 30,
                objetivo_especifico: 5,
              },
            ],
            codigo: 'SPO1',
            descripcion: 'Descripcion del Objetivo Especifico SPO1',
            supuestos: 'Sup',
            riesgos: 'Riesgos',
            proyecto: null,
            objetivo_general: 6,
          },
        ],
        codigo: 'OO',
        descripcion: 'Objetivo General',
        supuestos: 'Sup R',
        riesgos: 'ries og',
        proyecto: 6,
      },
    },
    indicadorog: [
      {
        tipo: 'indicadorog',
        data: {
          id: 27,
          codigo: 'IND002-OG',
          descripcion: 'IND002-OG',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '50',
          fechaTargetPoblacion: '2025-11-09',
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: null,
          baseline: '0',
          fechaLineaBase: '2025-09-11',
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          target_q4: null,
          fechaTargetQ4: null,
          polymorphic_ctype: 29,
          objetivo_general: 6,
        },
      },
      {
        tipo: 'indicadorog',
        data: {
          id: 28,
          codigo: 'IND0001-OG',
          descripcion: 'Descripcion del IND0001-OG',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '100',
          fechaTargetPoblacion: '2025-11-09',
          tipo: '1-9',
          frecuencia: 'CUATRIMESTRAL',
          responsable: null,
          baseline: '10',
          fechaLineaBase: '2025-09-01',
          target_q1: '30',
          fechaTargetQ1: '2025-09-17',
          target_q2: '40',
          fechaTargetQ2: '2025-10-01',
          target_q3: '50',
          fechaTargetQ3: '2025-10-08',
          target_q4: null,
          fechaTargetQ4: null,
          polymorphic_ctype: 29,
          objetivo_general: 6,
        },
      },
    ],
    objetivoespecifico: {
      tipo: 'objetivoespecifico',
      data: {
        id: 5,
        indicador_oe: [
          {
            id: 30,
            codigo: 'IND001-SPO1',
            descripcion: 'Descripcion del Indicador IND001-SPO1',
            redaccion: 'GUIA',
            fuente_verificacion: 'Listas',
            target_poblacion: '100',
            fechaTargetPoblacion: '2025-09-18',
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: '',
            baseline: '10',
            fechaLineaBase: null,
            target_q1: '',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 28,
            objetivo_especifico: 5,
          },
          {
            id: 31,
            codigo: 'IND00-SPO',
            descripcion: 'Descripcion',
            redaccion: 'GUIA',
            fuente_verificacion: '',
            target_poblacion: '',
            fechaTargetPoblacion: null,
            tipo: 'A-Z',
            frecuencia: 'MENSUAL',
            responsable: '',
            baseline: '',
            fechaLineaBase: null,
            target_q1: '',
            fechaTargetQ1: null,
            target_q2: '',
            fechaTargetQ2: null,
            target_q3: '',
            fechaTargetQ3: null,
            target_q4: null,
            fechaTargetQ4: null,
            polymorphic_ctype: 28,
            objetivo_especifico: 5,
          },
        ],
        resultados_oe: [
          {
            id: 8,
            indicador_res_oe: [
              {
                id: 29,
                codigo: 'IND00-RES00-SPO',
                descripcion: '',
                redaccion: 'GUIA',
                fuente_verificacion: '',
                target_poblacion: '',
                fechaTargetPoblacion: null,
                tipo: 'A-Z',
                frecuencia: 'MENSUAL',
                responsable: null,
                baseline: '',
                fechaLineaBase: null,
                target_q1: '',
                fechaTargetQ1: null,
                target_q2: '',
                fechaTargetQ2: null,
                target_q3: '',
                fechaTargetQ3: null,
                target_q4: null,
                fechaTargetQ4: null,
                polymorphic_ctype: 33,
                resultado_obj_especifico: 8,
              },
            ],
            productos_res_oe: [],
            proceso_resultado_oe: [],
            actividad_resultado_oe: [],
            codigo: 'RES002-SPO1',
            descripcion: 'Descripcion de RES002-SPO1',
            supuestos: 'SUp Res OE',
            riesgos: 'Riesg Res OE',
            polymorphic_ctype: 31,
            objetivo_especifico: 5,
          },
          {
            id: 9,
            indicador_res_oe: [],
            productos_res_oe: [],
            proceso_resultado_oe: [],
            actividad_resultado_oe: [],
            codigo: 'RES001-SPO1',
            descripcion: 'Descripcion del resultado RES001-SPO1',
            supuestos: 'SUp Res OE',
            riesgos: 'Riesg Res OE',
            polymorphic_ctype: 31,
            objetivo_especifico: 5,
          },
          {
            id: 10,
            indicador_res_oe: [],
            productos_res_oe: [
              {
                id: 4,
                codigo: 'PROD002-RES01-SPO1',
                descripcion: 'PROD002-RES01-SPO1',
                supuestos: 'sup prod',
                riesgos: 'risk prod',
                entregado: false,
                polymorphic_ctype: 32,
                objetivo_especifico: null,
              },
              {
                id: 5,
                codigo: 'PROD001-RES01-SPO1',
                descripcion: 'Descricipn  PROD001-RES01-SPO1',
                supuestos: 'sup prod',
                riesgos: 'risk prod',
                entregado: false,
                polymorphic_ctype: 32,
                objetivo_especifico: null,
              },
            ],
            proceso_resultado_oe: [
              {
                id: 5,
                actividades: [],
                codigo: 'PROC',
                titulo: 'Proceso Resultado OE',
                descripcion: '',
                resultado_og: null,
                resultado_oe: 10,
                producto_oe: null,
              },
            ],
            actividad_resultado_oe: [],
            codigo: 'RES003-SPO1',
            descripcion: 'Des Res OE RES01-SPO1',
            supuestos: 'SUp Res OE',
            riesgos: 'Riesg Res OE',
            polymorphic_ctype: 31,
            objetivo_especifico: 5,
          },
        ],
        productos_oe: [
          {
            id: 3,
            proceso_producto_oe: [],
            actividad_producto_oe: [],
            codigo: 'P001-SO1',
            descripcion: 'Descripcion de P001-SO1',
            supuestos: 'sup prod oe',
            riesgos: 'risk oe',
            entregado: false,
            polymorphic_ctype: 30,
            objetivo_especifico: 5,
          },
        ],
        codigo: 'SPO1',
        descripcion: 'Descripcion del Objetivo Especifico SPO1',
        supuestos: 'Sup',
        riesgos: 'Riesgos',
        proyecto: null,
        objetivo_general: 6,
      },
    },
    indicadoroe: {
      tipo: 'indicadoroe',
      data: {
        id: 30,
        codigo: 'IND001-SPO1',
        descripcion: 'Descripcion del Indicador IND001-SPO1',
        redaccion: 'GUIA',
        fuente_verificacion: 'Listas',
        target_poblacion: '100',
        fechaTargetPoblacion: '2025-09-18',
        tipo: 'A-Z',
        frecuencia: 'MENSUAL',
        responsable: '',
        baseline: '10',
        fechaLineaBase: null,
        target_q1: '',
        fechaTargetQ1: null,
        target_q2: '',
        fechaTargetQ2: null,
        target_q3: '',
        fechaTargetQ3: null,
        target_q4: null,
        fechaTargetQ4: null,
        polymorphic_ctype: 28,
        objetivo_especifico: 5,
      },
    },
    resultadooe: {
      tipo: 'resultadooe',
      data: {
        id: 9,
        indicador_res_oe: [],
        productos_res_oe: [],
        proceso_resultado_oe: [],
        actividad_resultado_oe: [],
        codigo: 'RES001-SPO1',
        descripcion: 'Descripcion del resultado RES001-SPO1',
        supuestos: 'SUp Res OE',
        riesgos: 'Riesg Res OE',
        polymorphic_ctype: 31,
        objetivo_especifico: 5,
      },
    },
    productoe: {
      tipo: 'productoe',
      data: {
        id: 3,
        proceso_producto_oe: [],
        actividad_producto_oe: [],
        codigo: 'P001-SO1',
        descripcion: 'Descripcion de P001-SO1',
        supuestos: 'sup prod oe',
        riesgos: 'risk oe',
        entregado: false,
        polymorphic_ctype: 30,
        objetivo_especifico: 5,
      },
    },
  },
  nodosRelacionados: [
    {
      id: '2',
      type: 'objetivogeneral',
      dimensions: {
        width: 700,
        height: 210,
      },
      computedPosition: {
        x: 1125,
        y: 650,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-2',
            type: 'source',
            nodeId: '2',
            position: 'bottom',
            x: 344,
            y: 203.75,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-2',
            type: 'target',
            nodeId: '2',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1125,
        y: 650,
      },
      data: {
        label: 'Objetivo General',
        type: 'objetivogeneral',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 6,
          codigo: 'OO',
          descripcion: 'Objetivo General',
          supuestos: 'Sup R',
          riesgos: 'ries og',
          proyecto: 6,
        },
      },
      events: {},
    },
    {
      id: '3',
      type: 'indicadorog',
      dimensions: {
        width: 700,
        height: 513,
      },
      computedPosition: {
        x: 375,
        y: 1300,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-3',
            type: 'source',
            nodeId: '3',
            position: 'bottom',
            x: 344,
            y: 506.9375,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-3',
            type: 'target',
            nodeId: '3',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 375,
        y: 1300,
      },
      data: {
        label: 'Indicador OG',
        type: 'indicadorog',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 27,
          codigo: 'IND002-OG',
          descripcion: 'IND002-OG',
          definicion: 'Definicion del indicador',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '50',
          fechaTargetPoblacion: '2025-11-09',
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: null,
          baseline: '0',
          fechaLineaBase: '2025-09-11',
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          objetivo_general: 6,
        },
      },
      events: {},
    },
    {
      id: '4',
      type: 'indicadorog',
      dimensions: {
        width: 700,
        height: 513,
      },
      computedPosition: {
        x: 1125,
        y: 1300,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-4',
            type: 'source',
            nodeId: '4',
            position: 'bottom',
            x: 344,
            y: 506.9375,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-4',
            type: 'target',
            nodeId: '4',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1125,
        y: 1300,
      },
      data: {
        label: 'Indicador OG',
        type: 'indicadorog',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 28,
          codigo: 'IND0001-OG',
          descripcion: 'Descripcion del IND0001-OG',
          redaccion: 'SMART',
          fuente_verificacion: 'Fuentes de verificacion',
          target_poblacion: '100',
          fechaTargetPoblacion: '2025-11-09',
          tipo: '1-9',
          frecuencia: 'CUATRIMESTRAL',
          responsable: null,
          baseline: '10',
          fechaLineaBase: '2025-09-01',
          target_q1: '30',
          fechaTargetQ1: '2025-09-17',
          target_q2: '40',
          fechaTargetQ2: '2025-10-01',
          target_q3: '50',
          fechaTargetQ3: '2025-10-08',
          objetivo_general: 6,
        },
      },
      events: {},
    },
    {
      id: '9',
      type: 'indicadoroe',
      dimensions: {
        width: 700,
        height: 513,
      },
      computedPosition: {
        x: 1500,
        y: 1950,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-9',
            type: 'source',
            nodeId: '9',
            position: 'bottom',
            x: 344,
            y: 506.9375,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-9',
            type: 'target',
            nodeId: '9',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 1500,
        y: 1950,
      },
      data: {
        label: 'Indicador OE',
        type: 'indicadoroe',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 30,
          codigo: 'IND001-SPO1',
          descripcion: 'Descripcion del Indicador IND001-SPO1',
          redaccion: 'GUIA',
          fuente_verificacion: 'Listas',
          target_poblacion: '100',
          fechaTargetPoblacion: '2025-09-18',
          tipo: 'A-Z',
          frecuencia: 'MENSUAL',
          responsable: '',
          baseline: '10',
          fechaLineaBase: null,
          target_q1: '',
          fechaTargetQ1: null,
          target_q2: '',
          fechaTargetQ2: null,
          target_q3: '',
          fechaTargetQ3: null,
          objetivo_especifico: 5,
        },
      },
      events: {},
    },
    {
      id: '7',
      type: 'resultadooe',
      dimensions: {
        width: 700,
        height: 210,
      },
      computedPosition: {
        x: 750,
        y: 1950,
        z: 0,
      },
      handleBounds: {
        source: [
          {
            id: 'source-7',
            type: 'source',
            nodeId: '7',
            position: 'bottom',
            x: 344,
            y: 203.75,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-7',
            type: 'target',
            nodeId: '7',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: {
        x: 750,
        y: 1950,
      },
      data: {
        label: 'Resultado OE',
        type: 'resultadooe',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 9,
          codigo: 'RES001-SPO1',
          descripcion: 'Descripcion del resultado RES001-SPO1',
          supuestos: 'SUp Res OE',
          riesgos: 'Riesg Res OE',
          proceso: null,
          objetivo_especifico: 5,
        },
      },
      events: {},
    },
  ],
  seleccionesSimples: {
    objetivoGeneralId: 6,
    indicadorOGIds: [27, 28],
    objetivoEspecificoId: 5,
    indicadorOEId: 30,
    resultadoOEId: 9,
    productoOEId: 3,
  },
})
</script>

<style lang="scss" scoped></style>
