<script setup>
import { ref } from 'vue'
import { useVueFlow, VueFlow } from '@vue-flow/core'

const { onInit, findNode, fitView, snapToGrid } = useVueFlow()

const nodes = ref([
  {
    id: '1',
    type: 'proyecto',
    dimensions: { width: 700, height: 350 },
    computedPosition: { x: 96, y: -282, z: 0 },
    handleBounds: {
      source: [
        {
          id: 'source-1',
          type: 'source',
          nodeId: '1',
          position: 'bottom',
          x: 343.9998557186057,
          y: 343.4999162538225,
          width: 12,
          height: 12,
        },
      ],
      target: null,
    },
    selected: false,
    dragging: false,
    resizing: false,
    initialized: false,
    isParent: false,
    position: { x: 96, y: -282 },
    data: {
      label: 'Proyecto',
      type: 'proyecto',
      estado: 'ES',
      datosNodo: {
        id: 6,
        codigo: 'TST2',
        titulo: 'Tesde 2',
        descripcion: 'dasdas',
        fecha_creacion: '2025-08-21T14:37:18.400099+00:00',
        fecha_inicio: null,
        fecha_finalizacion: null,
        presupuesto: '54654.00',
        estado: 'EP',
        creado_por: 'Admin',
        pei: 1,
        instancia_gestora: [5],
        procedencia_fondos: [1],
      },
    },
    events: {},
  },
  {
    id: '2',
    type: 'objetivogeneral',
    dimensions: { width: 700, height: 210 },
    computedPosition: { x: 60, y: 202, z: 0 },
    handleBounds: {
      source: [
        {
          id: 'source-2',
          type: 'source',
          nodeId: '2',
          position: 'bottom',
          x: 344,
          y: 203.75,
          width: 12,
          height: 12,
        },
      ],
      target: [
        {
          id: 'source-2',
          type: 'target',
          nodeId: '2',
          position: 'top',
          x: 344,
          y: -6,
          width: 12,
          height: 12,
        },
      ],
    },
    selected: false,
    dragging: false,
    resizing: false,
    initialized: false,
    isParent: false,
    position: { x: 60, y: 202 },
    data: {
      label: 'Objetivo General',
      type: 'objetivogeneral',
      estado: 'ES',
      mapaNodoId: '6',
      nodoProyecto: {
        id: 6,
        codigo: 'OO',
        descripcion: 'desc og',
        supuestos: 'sup og',
        riesgos: 'ries og',
        proyecto: 6,
      },
    },
    events: {},
  },
  {
    id: '3',
    type: 'resultadoog',
    dimensions: { width: 700, height: 210 },
    computedPosition: { x: 240, y: 478, z: 1000 },
    handleBounds: {
      source: [
        {
          id: 'source-3',
          type: 'source',
          nodeId: '3',
          position: 'bottom',
          x: 344,
          y: 203.75,
          width: 12,
          height: 12,
        },
      ],
      target: [
        {
          id: 'source-3',
          type: 'target',
          nodeId: '3',
          position: 'top',
          x: 344,
          y: -6,
          width: 12,
          height: 12,
        },
      ],
    },
    selected: true,
    dragging: false,
    resizing: false,
    initialized: false,
    isParent: false,
    position: { x: 240, y: 478 },
    data: {
      label: 'Resultado OG',
      type: 'resultadoog',
      mapaNodoId: '6',
      nodoProyecto: {
        id: 8,
        codigo: 'R0',
        descripcion: 'Descripcion del resultado de obj gral',
        supuestos: 'sup res obj gral',
        riesgos: 'riesg res obj gral',
        objetivo_general: 6,
      },
    },
    events: {},
  },
  {
    id: '4',
    type: 'actividadrog',
    dimensions: { width: 0, height: 0 },
    computedPosition: { z: 0, x: 0, y: 0 },
    handleBounds: { source: [], target: [] },
    selected: false,
    dragging: false,
    resizing: false,
    initialized: false,
    isParent: false,
    position: { x: 0, y: 0 },
    data: {
      label: 'Actividad Res. OG',
      type: 'actividadrog',
      mapaNodoId: '6',
      nodoProyecto: {
        id: 47,
        codigo: 'ACT',
        descripcion: '',
        tipo: null,
        fecha_programada: null,
        fecha_inicio: null,
        fecha_cierre: null,
        presupuesto: null,
        estado: 'CRD',
        procedencia_fondos: null,
        objetivo_de_actividad: '',
        descripcion_evaluacion: '',
        proceso: null,
        resultado_og: null,
        resultado_oe: null,
        producto_oe: null,
        responsable: null,
        proyecto: 6,
      },
    },
    events: {},
  },
])

const edges = ref([
  {
    id: 'edge-1',
    type: 'default',
    source: '1',
    target: '2',
    data: {},
    events: {},
    label: 'Conexion',
    animated: true,
    sourceNode: {
      id: '1',
      type: 'proyecto',
      dimensions: { width: 700, height: 350 },
      computedPosition: { x: 96, y: -282, z: 0 },
      handleBounds: {
        source: [
          {
            id: 'source-1',
            type: 'source',
            nodeId: '1',
            position: 'bottom',
            x: 343.9998557186057,
            y: 343.4999162538225,
            width: 12,
            height: 12,
          },
        ],
        target: null,
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: { x: 96, y: -282 },
      data: {
        label: 'Proyecto',
        type: 'proyecto',
        estado: 'ES',
        datosNodo: {
          id: 6,
          codigo: 'TST2',
          titulo: 'Tesde 2',
          descripcion: 'dasdas',
          fecha_creacion: '2025-08-21T14:37:18.400099+00:00',
          fecha_inicio: null,
          fecha_finalizacion: null,
          presupuesto: '54654.00',
          estado: 'EP',
          creado_por: 'Admin',
          pei: 1,
          instancia_gestora: [5],
          procedencia_fondos: [1],
        },
      },
      events: {},
    },
    targetNode: {
      id: '2',
      type: 'objetivogeneral',
      dimensions: { width: 700, height: 210 },
      computedPosition: { x: 60, y: 202, z: 0 },
      handleBounds: {
        source: [
          {
            id: 'source-2',
            type: 'source',
            nodeId: '2',
            position: 'bottom',
            x: 344,
            y: 203.75,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-2',
            type: 'target',
            nodeId: '2',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: { x: 60, y: 202 },
      data: {
        label: 'Objetivo General',
        type: 'objetivogeneral',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 6,
          codigo: 'OO',
          descripcion: 'desc og',
          supuestos: 'sup og',
          riesgos: 'ries og',
          proyecto: 6,
        },
      },
      events: {},
    },
    sourceX: 445.9998557186057,
    sourceY: 73.4999162538225,
    targetX: 410,
    targetY: 196,
  },
  {
    id: 'edge-2',
    type: 'default',
    source: '2',
    target: '3',
    data: {},
    events: {},
    label: 'Conexion',
    animated: true,
    sourceNode: {
      id: '2',
      type: 'objetivogeneral',
      dimensions: { width: 700, height: 210 },
      computedPosition: { x: 60, y: 202, z: 0 },
      handleBounds: {
        source: [
          {
            id: 'source-2',
            type: 'source',
            nodeId: '2',
            position: 'bottom',
            x: 344,
            y: 203.75,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-2',
            type: 'target',
            nodeId: '2',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: { x: 60, y: 202 },
      data: {
        label: 'Objetivo General',
        type: 'objetivogeneral',
        estado: 'ES',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 6,
          codigo: 'OO',
          descripcion: 'desc og',
          supuestos: 'sup og',
          riesgos: 'ries og',
          proyecto: 6,
        },
      },
      events: {},
    },
    targetNode: {
      id: '3',
      type: 'resultadoog',
      dimensions: { width: 700, height: 210 },
      computedPosition: { x: 240, y: 478, z: 1000 },
      handleBounds: {
        source: [
          {
            id: 'source-3',
            type: 'source',
            nodeId: '3',
            position: 'bottom',
            x: 344,
            y: 203.75,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-3',
            type: 'target',
            nodeId: '3',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: true,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: { x: 240, y: 478 },
      data: {
        label: 'Resultado OG',
        type: 'resultadoog',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 8,
          codigo: 'R0',
          descripcion: 'Descripcion del resultado de obj gral',
          supuestos: 'sup res obj gral',
          riesgos: 'riesg res obj gral',
          objetivo_general: 6,
        },
      },
      events: {},
    },
    sourceX: 410,
    sourceY: 417.75,
    targetX: 590,
    targetY: 472,
  },
  {
    id: 'edge-3',
    type: 'default',
    source: '3',
    target: '4',
    data: {},
    events: {},
    label: 'Conexion',
    animated: true,
    sourceNode: {
      id: '3',
      type: 'resultadoog',
      dimensions: { width: 700, height: 210 },
      computedPosition: { x: 240, y: 478, z: 1000 },
      handleBounds: {
        source: [
          {
            id: 'source-3',
            type: 'source',
            nodeId: '3',
            position: 'bottom',
            x: 344,
            y: 203.75,
            width: 12,
            height: 12,
          },
        ],
        target: [
          {
            id: 'source-3',
            type: 'target',
            nodeId: '3',
            position: 'top',
            x: 344,
            y: -6,
            width: 12,
            height: 12,
          },
        ],
      },
      selected: true,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: { x: 240, y: 478 },
      data: {
        label: 'Resultado OG',
        type: 'resultadoog',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 8,
          codigo: 'R0',
          descripcion: 'Descripcion del resultado de obj gral',
          supuestos: 'sup res obj gral',
          riesgos: 'riesg res obj gral',
          objetivo_general: 6,
        },
      },
      events: {},
    },
    targetNode: {
      id: '4',
      type: 'actividadrog',
      dimensions: { width: 0, height: 0 },
      computedPosition: { z: 0, x: 0, y: 0 },
      handleBounds: { source: [], target: [] },
      selected: false,
      dragging: false,
      resizing: false,
      initialized: false,
      isParent: false,
      position: { x: 0, y: 0 },
      data: {
        label: 'Actividad Res. OG',
        type: 'actividadrog',
        mapaNodoId: '6',
        nodoProyecto: {
          id: 47,
          codigo: 'ACT',
          descripcion: '',
          tipo: null,
          fecha_programada: null,
          fecha_inicio: null,
          fecha_cierre: null,
          presupuesto: null,
          estado: 'CRD',
          procedencia_fondos: null,
          objetivo_de_actividad: '',
          descripcion_evaluacion: '',
          proceso: null,
          resultado_og: null,
          resultado_oe: null,
          producto_oe: null,
          responsable: null,
          proyecto: 6,
        },
      },
      events: {},
    },
  },
])

// to enable snapping to grid
snapToGrid.value = true

// any event that is emitted from the `<VueFlow />` component can be listened to using the `onEventName` method
onInit((instance) => {
  // `instance` is the same type as the return of `useVueFlow` (VueFlowStore)

  fitView()

  const node = findNode('1')

  if (node) {
    node.position = { x: 100, y: 100 }
  }
})
</script>

<template>
  <VueFlow :nodes="nodes" :edges="edges" />
</template>
